version: "3.9"

services:
  # Banco de dados PostgreSQL
  db:
    image: postgres:15
    container_name: gymDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
