# =========================
# Google API (produção)
# =========================
api.security.token.secret=${JWT_SECRET:mysecret}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}

# =========================
# Conexão com banco em produção
# =========================
spring.datasource.url=jdbc:postgresql://interchange.proxy.rlwy.net:59347/railway
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# Porta do servidor
# =========================
server.port=${PORT:8080}
