spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATABASE_URL}              # Variável do Railway
    username: ${DATABASE_USER}        # Variável do Railway
    password: ${DATABASE_PASSWORD}    # Variável do Railway
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 10000
      connection-timeout: 20000
      max-lifetime: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

api:
  security:
    token:
      secret: ${JWT_SECRET:mysecret}  # Default "mysecret" caso não esteja setado no Ra_
