spring.application.name=gym-organizer
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google OAuth (dev)
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# Banco local
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=xNlDoAlaykurJXOCbcRrfzqmEvOuTwNL
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8080

spring.profiles.active=prod
